name: Checks
on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Docker Build
        run: docker-compose build --build-arg DEV=true

      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      
      - name: Install flake8
        run: docker-compose run --rm app sh -c "pip install flake8"
      
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
